spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:todo;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: true
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    locations: classpath:db/migration
  mail:
    host: smtp.qq.com
    port: 465
    username: 836230953@qq.com
    password: fdlekbzskixsbecb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false
      mail.smtp.ssl.enable: true
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.example.todo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG
